### ISSUE TITLE
项目报错找不到NeZhaModel模块

### ISSUE THREAD

**Issue by chengzhongnan** [cyberfish1120/PaddleTDS#1]
你好，程序在运行的时候出现以下错误
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from ner_code.predict import NerPredict
  File "/home/aistudio/PaddleTDS-master/ner_code/predict.py", line 5, in <module>
    from ner_code.ner_utils import model, utils_fn
  File "/home/aistudio/PaddleTDS-master/ner_code/ner_utils/model.py", line 5, in <module>
    from paddlenlp.transformers import NeZhaModel
ImportError: cannot import name 'NeZhaModel' from 'paddlenlp.transformers' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/__init__.py)
请问是还需要安装什么包吗？

**Comment by chengzhongnan** [comment]
不好意思，是我自己没有启动GPU环境
